---
- hosts: localhost
  name: "Manage Route53"
  gather_facts: no
  tasks:
    - route53:
        command: create
        zone: webitel.com
        record: demo-for-webinar.webitel.com
        type: A
        ttl: 7200
        value: '{{ IP }}'
      tags: ['add']
    - route53:
        command: delete                                      
        zone: webitel.com
        record: demo-for-webinar.webitel.com
        type: A
        ttl: 7200
        value: '{{ IP }}'
      tags: ['del']


- hosts: webitel
  name: "Copy PEM files"
  tags: ['ssl']
  gather_facts: no
  tasks:
    - copy: src=ssl dest=/opt/webitel/ mode=0666

- hosts: webitel
  name: "Add swap file"
  tags: ['swap']
  gather_facts: no
  tasks:
    - command: dd if=/dev/zero of=/swapfile bs=1024 count=1024k 
    - file: path=/swapfile owner=root group=root mode=0600
    - command: file /swapfile
      register: swapfile
    - command: mkswap /swapfile
      when: swapfile.stdout.find('swap file') == -1
    - mount: name=none
        src=/swapfile
        fstype=swap
        opts=sw
        passno=0
        dump=0
        state=present
    - command: swapon /swapfile
